# Generated by Django 5.0 on 2023-12-19 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dataset', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='HavanaSeaZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demand', models.CharField(blank=True, max_length=10, null=True)),
                ('modification', models.CharField(blank=True, max_length=10, null=True)),
                ('nationality', models.CharField(blank=True, max_length=10, null=True)),
                ('merchant', models.CharField(blank=True, max_length=10, null=True)),
                ('location', models.CharField(blank=True, max_length=10, null=True)),
                ('board', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='board.board')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NassauSeaZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demand', models.CharField(blank=True, max_length=10, null=True)),
                ('modification', models.CharField(blank=True, max_length=10, null=True)),
                ('nationality', models.CharField(blank=True, max_length=10, null=True)),
                ('merchant', models.CharField(blank=True, max_length=10, null=True)),
                ('location', models.CharField(blank=True, max_length=10, null=True)),
                ('board', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='board.board')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrackAtWar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_left', models.CharField(max_length=20)),
                ('section_right', models.CharField(max_length=20)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.board')),
            ],
        ),
        migrations.CreateModel(
            name='TrackEnemyHitLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hull', models.IntegerField(default=0)),
                ('cargo', models.IntegerField(default=0)),
                ('masts', models.IntegerField(default=0)),
                ('crew', models.IntegerField(default=0)),
                ('cannons', models.IntegerField(default=0)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.board')),
            ],
        ),
        migrations.CreateModel(
            name='TrackGloryPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blue_player', models.IntegerField(default=0)),
                ('green_player', models.IntegerField(default=0)),
                ('red_player', models.IntegerField(default=0)),
                ('yellow_player', models.IntegerField(default=0)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.board')),
            ],
        ),
        migrations.CreateModel(
            name='TrackMerchantToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.BooleanField(default=False)),
                ('second', models.BooleanField(default=False)),
                ('thirth', models.BooleanField(default=False)),
                ('fourth', models.BooleanField(default=False)),
                ('fifth', models.BooleanField(default=False)),
                ('sixth', models.BooleanField(default=False)),
                ('seventh', models.BooleanField(default=False)),
                ('eighth', models.BooleanField(default=False)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.board')),
            ],
        ),
        migrations.CreateModel(
            name='TrackMissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.board')),
                ('card_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mission_one', to='dataset.missionsdeck')),
                ('card_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mission_two', to='dataset.missionsdeck')),
            ],
        ),
    ]
