# Generated by Django 5.0 on 2023-12-21 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_board_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='board',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
