# Generated by Django 5.0 on 2023-12-21 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_board_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='board',
            field=models.ImageField(blank=True, null=True, upload_to='board/'),
        ),
    ]
