# Generated by Django 5.0 on 2023-12-21 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_alter_board_board'),
        ('dataset', '0005_captaincard_deck_eventcard_glorycard_missioncard_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackmissions',
            name='card_one',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mission_one', to='dataset.missioncard'),
        ),
        migrations.AlterField(
            model_name='trackmissions',
            name='card_two',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mission_two', to='dataset.missioncard'),
        ),
    ]
