# Generated by Django 5.0 on 2023-12-22 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_alter_trackmissions_card_one_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeaZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sea_zone_name', models.CharField(max_length=50)),
                ('sea_zone_coordinates', models.CharField(max_length=500)),
                ('name_cx', models.IntegerField()),
                ('name_rx', models.IntegerField()),
                ('name_cy', models.IntegerField()),
                ('name_rotate', models.IntegerField()),
                ('feature_coordinates', models.CharField(max_length=500)),
                ('demand_x', models.IntegerField()),
                ('demand_y', models.IntegerField()),
                ('demand_rotate', models.IntegerField()),
                ('modification_x', models.IntegerField()),
                ('modification_y', models.IntegerField()),
                ('modification_rotate', models.IntegerField()),
                ('nationality_x', models.IntegerField()),
                ('nationality_y', models.IntegerField()),
                ('nationality_rotate', models.IntegerField()),
                ('merchant_x', models.IntegerField()),
                ('merchant_y', models.IntegerField()),
                ('location_x', models.IntegerField()),
                ('location_y', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='nassauseazone',
            name='board',
        ),
        migrations.DeleteModel(
            name='HavanaSeaZone',
        ),
        migrations.DeleteModel(
            name='NassauSeaZone',
        ),
    ]
