# Generated by Django 5.0 on 2023-12-22 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_seazone_remove_nassauseazone_board_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seazone',
            options={'verbose_name': 'Sea Zones'},
        ),
    ]
