# Generated by Django 5.0 on 2023-12-22 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_alter_seazone_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'verbose_name': 'Board'},
        ),
        migrations.AlterModelOptions(
            name='seazone',
            options={'verbose_name': 'Sea Zone'},
        ),
    ]
