# Generated by Django 5.0 on 2023-12-22 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_alter_board_options_alter_seazone_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='seazone',
            name='name_ry',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
