# Generated by Django 5.0 on 2024-01-04 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0010_seazone_name_ry'),
    ]

    operations = [
        migrations.AddField(
            model_name='seazone',
            name='mission_sign_x',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seazone',
            name='mission_sign_y',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
