# Generated by Django 5.0 on 2024-01-11 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0011_seazone_mission_sign_x_seazone_mission_sign_y'),
    ]

    operations = [
        migrations.AddField(
            model_name='seazone',
            name='e_direction',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='seazone',
            name='n_direction',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='seazone',
            name='ne_direction',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='seazone',
            name='nw_direction',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='seazone',
            name='s_direction',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='seazone',
            name='se_direction',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='seazone',
            name='sw_direction',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='seazone',
            name='w_direction',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
