# Generated by Django 5.0 on 2024-01-23 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0014_seazone_feature_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seazone',
            name='feature_text',
        ),
        migrations.AddField(
            model_name='seazone',
            name='feature_image',
            field=models.ImageField(blank=True, null=True, upload_to='featureImages/'),
        ),
    ]
