# Generated by Django 5.0 on 2024-03-27 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0016_alter_seazone_e_direction_alter_seazone_n_direction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seazone',
            name='port_nationality',
            field=models.CharField(blank=True, choices=[('Dutch', 'Dutch'), ('French', 'French'), ('English', 'English'), ('Spanish', 'Spanish')], max_length=50, null=True),
        ),
    ]
