# Generated by Django 5.0 on 2025-01-24 05:11

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CombatFlowDiagram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(default="Combat Flow Diagram", max_length=150),
                ),
                (
                    "diagram",
                    models.ImageField(blank=True, null=True, upload_to="battleApp/"),
                ),
            ],
        ),
    ]
