# Generated by Django 5.0 on 2025-02-19 05:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("battle_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CombatFlow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("aggressor", models.CharField(max_length=30)),
                ("defender", models.CharField(max_length=30)),
            ],
        ),
    ]
