# Generated by Django 5.0 on 2025-02-19 05:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("battle_app", "0002_combatflow"),
    ]

    operations = [
        migrations.AddField(
            model_name="combatflow",
            name="round",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="combatflow",
            name="aggressor",
            field=models.CharField(
                blank=True,
                choices=[
                    ("player", "player"),
                    ("npc", "npc"),
                    ("location", "location"),
                    ("fort", "fort"),
                ],
                max_length=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="combatflow",
            name="defender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("player", "player"),
                    ("npc", "npc"),
                    ("location", "location"),
                    ("fort", "fort"),
                ],
                max_length=30,
                null=True,
            ),
        ),
    ]
