# Generated by Django 5.0 on 2025-02-19 05:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("battle_app", "0003_combatflow_round_alter_combatflow_aggressor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="combatflow",
            name="aggressor_leadership",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="combatflow",
            name="aggressor_seamanship",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="combatflow",
            name="defender_leadership",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="combatflow",
            name="defender_seamanship",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
