# Generated by Django 5.0 on 2025-02-19 05:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("battle_app", "0004_combatflow_aggressor_leadership_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="combatflow",
            name="aggerssor_declaration",
            field=models.CharField(
                blank=True,
                choices=[("shoot", "shoot"), ("board", "board"), ("flee", "flee")],
                max_length=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="combatflow",
            name="defender_declaration",
            field=models.CharField(
                blank=True,
                choices=[("shoot", "shoot"), ("board", "board"), ("flee", "flee")],
                max_length=30,
                null=True,
            ),
        ),
    ]
