# Generated by Django 5.0 on 2025-02-19 05:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("battle_app", "0005_combatflow_aggerssor_declaration_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="combatflow",
            name="aggressor_stat",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name="combatflow",
            name="defender_stat",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
