# Generated by Django 5.0 on 2025-02-19 06:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("battle_app", "0006_combatflow_aggressor_stat_combatflow_defender_stat"),
    ]

    operations = [
        migrations.AddField(
            model_name="combatflow",
            name="combat",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
