# Generated by Django 5.0 on 2025-02-19 06:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("battle_app", "0007_combatflow_combat"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="combatflow",
            name="aggressor_stat",
        ),
        migrations.RemoveField(
            model_name="combatflow",
            name="defender_stat",
        ),
    ]
