# Generated by Django 5.0 on 2025-02-19 07:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("battle_app", "0008_remove_combatflow_aggressor_stat_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="combatflow",
            name="aggerssor_declaration",
        ),
        migrations.RemoveField(
            model_name="combatflow",
            name="aggressor",
        ),
        migrations.RemoveField(
            model_name="combatflow",
            name="aggressor_leadership",
        ),
        migrations.RemoveField(
            model_name="combatflow",
            name="aggressor_seamanship",
        ),
        migrations.RemoveField(
            model_name="combatflow",
            name="defender",
        ),
        migrations.RemoveField(
            model_name="combatflow",
            name="defender_declaration",
        ),
        migrations.RemoveField(
            model_name="combatflow",
            name="defender_leadership",
        ),
        migrations.RemoveField(
            model_name="combatflow",
            name="defender_seamanship",
        ),
        migrations.RemoveField(
            model_name="combatflow",
            name="round",
        ),
    ]
