# Generated by Django 5.0 on 2025-03-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("battle_app", "0009_remove_combatflow_aggerssor_declaration_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="combatflow",
            name="combat",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
