# Generated by Django 5.0 on 2025-03-20 10:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("battle_app", "0010_alter_combatflow_combat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="combatflow",
            name="combat",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
