# Generated by Django 5.0 on 2023-12-19 18:52

import game.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=game.models.Game.random_number_game, unique=True)),
                ('amount_players', models.IntegerField(default=1)),
                ('rounds', models.IntegerField(default=0)),
            ],
        ),
    ]
