# Generated by Django 5.0 on 2023-12-25 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='rounds',
        ),
        migrations.CreateModel(
            name='DBGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rounds', models.IntegerField(default=0)),
                ('basse_terre_ship_modification', models.CharField(blank=True, max_length=500, null=True)),
                ('basse_terre_demand_token', models.CharField(blank=True, max_length=500, null=True)),
                ('basse_terre_merchant_token', models.CharField(blank=True, max_length=500, null=True)),
                ('basse_terre_nationality_port', models.CharField(blank=True, max_length=500, null=True)),
                ('basse_terre_location_token', models.CharField(blank=True, max_length=500, null=True)),
                ('glory_point_blue', models.IntegerField(blank=True, default=0, null=True)),
                ('glory_point_green', models.IntegerField(blank=True, default=0, null=True)),
                ('glory_point_red', models.IntegerField(blank=True, default=0, null=True)),
                ('glory_point_yellow', models.IntegerField(blank=True, default=0, null=True)),
                ('at_war_section_left', models.CharField(blank=True, max_length=200, null=True)),
                ('at_war_section_right', models.CharField(blank=True, max_length=200, null=True)),
                ('hull_enemy_hit_location', models.IntegerField(blank=True, default=1, null=True)),
                ('cargo_enemy_hit_location', models.IntegerField(blank=True, default=1, null=True)),
                ('masts_enemy_hit_location', models.IntegerField(blank=True, default=1, null=True)),
                ('crew_enemy_hit_location', models.IntegerField(blank=True, default=1, null=True)),
                ('cannons_enemy_hit_location', models.IntegerField(blank=True, default=1, null=True)),
                ('merchants_track', models.IntegerField(blank=True, default=0, null=True)),
                ('game_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.game')),
            ],
        ),
    ]
