# Generated by Django 5.0 on 2023-12-25 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataset', '0023_remove_eventcard_rewers'),
        ('game', '0003_delete_dbgame'),
    ]

    operations = [
        migrations.CreateModel(
            name='StackEventsCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.IntegerField(default=0)),
                ('event_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataset.eventcard')),
            ],
        ),
    ]
