# Generated by Django 5.0 on 2023-12-25 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_stackeventscards'),
    ]

    operations = [
        migrations.AddField(
            model_name='stackeventscards',
            name='game_round',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stackeventscards',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.game'),
        ),
    ]
