# Generated by Django 5.0 on 2023-12-25 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_stackeventscards_game_round_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stackeventscards',
            name='game',
            field=models.ForeignKey(default=100, on_delete=django.db.models.deletion.CASCADE, to='game.game'),
        ),
    ]
