# Generated by Django 5.0 on 2023-12-25 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_alter_stackeventscards_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stackeventscards',
            name='game',
            field=models.ForeignKey(blank=True, default=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.game'),
        ),
    ]
