# Generated by Django 5.0 on 2024-01-04 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_alter_trackenemyhitlocations_cannons_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackenemyhitlocations',
            name='game_number',
            field=models.ForeignKey(blank=True, default=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.game'),
        ),
    ]
