# Generated by Django 5.0 on 2024-01-04 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_alter_trackenemyhitlocations_hull'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackenemyhitlocations',
            name='hull',
            field=models.IntegerField(default=1),
        ),
    ]
