# Generated by Django 5.0 on 2024-01-04 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataset', '0033_alter_sign_image'),
        ('game', '0016_stackmissionscards'),
    ]

    operations = [
        migrations.AddField(
            model_name='stackmissionscards',
            name='mission_2_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mission_2', to='dataset.missioncard'),
        ),
        migrations.AddField(
            model_name='stackmissionscards',
            name='mission_3_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mission_3', to='dataset.missioncard'),
        ),
        migrations.AlterField(
            model_name='stackmissionscards',
            name='mission_1_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mission_1', to='dataset.missioncard'),
        ),
    ]
