# Generated by Django 5.0 on 2024-01-04 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0017_stackmissionscards_mission_2_card_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stackmissionscards',
            name='game_round',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
