# Generated by Django 5.0 on 2024-01-04 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0019_trackglorypoint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackglorypoint',
            name='player_1',
        ),
        migrations.RemoveField(
            model_name='trackglorypoint',
            name='player_2',
        ),
        migrations.RemoveField(
            model_name='trackglorypoint',
            name='player_3',
        ),
        migrations.RemoveField(
            model_name='trackglorypoint',
            name='player_4',
        ),
        migrations.AddField(
            model_name='trackglorypoint',
            name='player_blue',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trackglorypoint',
            name='player_green',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trackglorypoint',
            name='player_red',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trackglorypoint',
            name='player_yellow',
            field=models.IntegerField(default=0),
        ),
    ]
