# Generated by Django 5.0 on 2024-01-05 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0020_remove_trackglorypoint_player_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackenemyhitlocations',
            name='cannons',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='trackenemyhitlocations',
            name='cargo',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='trackenemyhitlocations',
            name='crew',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='trackenemyhitlocations',
            name='masts',
            field=models.IntegerField(default=1),
        ),
    ]
