# Generated by Django 5.0 on 2024-01-05 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0021_alter_trackenemyhitlocations_cannons_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='amount_players',
            field=models.IntegerField(default=4),
        ),
    ]
