# Generated by Django 5.0 on 2024-01-06 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0023_trackloyality'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackFavors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_round', models.IntegerField(default=0)),
                ('player_blue', models.IntegerField(default=0)),
                ('player_green', models.IntegerField(default=0)),
                ('player_red', models.IntegerField(default=0)),
                ('player_yellow', models.IntegerField(default=0)),
                ('game_number', models.ForeignKey(blank=True, default=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.game')),
            ],
        ),
    ]
