# Generated by Django 5.0 on 2024-01-06 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0024_trackfavors'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackPlayerHitLocations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_round', models.IntegerField(default=0)),
                ('player_colour', models.CharField(blank=True, choices=[('Blue', 'Blue'), ('Green', 'Green'), ('Red', 'Red'), ('Yellow', 'Yellow')], max_length=20, null=True)),
                ('hull', models.IntegerField(default=1)),
                ('cargo', models.IntegerField(default=1)),
                ('masts', models.IntegerField(default=1)),
                ('crew', models.IntegerField(default=1)),
                ('cannons', models.IntegerField(default=1)),
                ('game_number', models.ForeignKey(blank=True, default=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.game')),
            ],
        ),
    ]
