# Generated by Django 5.0 on 2024-01-06 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataset', '0043_shipcard_boats_shipcard_speed'),
        ('game', '0026_trackplayergolds'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayersShipsCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_round', models.IntegerField(default=0)),
                ('game_number', models.ForeignKey(blank=True, default=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.game')),
                ('player_blue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_blue_ship_card', to='dataset.shipcard')),
                ('player_green', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_green_ship_card', to='dataset.shipcard')),
                ('player_red', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_red_ship_card', to='dataset.shipcard')),
                ('player_yellow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_yellow_ship_card', to='dataset.shipcard')),
            ],
        ),
    ]
