# Generated by Django 5.0 on 2024-01-06 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataset', '0045_remove_glorycard_rewers_alter_glorycard_notes'),
        ('game', '0028_playerscaptainscards'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayersGloryCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_round', models.IntegerField(default=0)),
                ('game_number', models.ForeignKey(blank=True, default=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.game')),
                ('player_blue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_blue_glory_card', to='dataset.glorycard')),
                ('player_green', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_green_glory_card', to='dataset.glorycard')),
                ('player_red', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_red_glory_card', to='dataset.glorycard')),
                ('player_yellow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_yellow_glory_card', to='dataset.glorycard')),
            ],
        ),
    ]
