# Generated by Django 5.0 on 2024-01-08 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0031_remove_trackplayergolds_amount_gold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='demands_token',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
