# Generated by Django 5.0 on 2024-01-08 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0037_alter_game_demands_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='demands_token',
        ),
        migrations.AddField(
            model_name='game',
            name='demand_token_basse_terre',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='demand_token_bridgetown',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='demand_token_caracas',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='demand_token_cartagena',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='demand_token_curacao',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='demand_token_havana',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='demand_token_nassau',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='demand_token_old_providence',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='demand_token_petite_goave',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='demand_token_port_royal',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='demand_token_san_juan',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='demand_token_santo_domingo',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='demand_token_st_john',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='demand_token_st_maarten',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='demand_token_tortuga',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='demand_token_trinidad',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
