# Generated by Django 5.0 on 2024-01-08 14:40

import game.models.game
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0038_remove_game_demands_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='demand_token_basse_terre',
        ),
        migrations.RemoveField(
            model_name='game',
            name='demand_token_bridgetown',
        ),
        migrations.RemoveField(
            model_name='game',
            name='demand_token_caracas',
        ),
        migrations.RemoveField(
            model_name='game',
            name='demand_token_cartagena',
        ),
        migrations.RemoveField(
            model_name='game',
            name='demand_token_curacao',
        ),
        migrations.RemoveField(
            model_name='game',
            name='demand_token_havana',
        ),
        migrations.RemoveField(
            model_name='game',
            name='demand_token_nassau',
        ),
        migrations.RemoveField(
            model_name='game',
            name='demand_token_old_providence',
        ),
        migrations.RemoveField(
            model_name='game',
            name='demand_token_petite_goave',
        ),
        migrations.RemoveField(
            model_name='game',
            name='demand_token_port_royal',
        ),
        migrations.RemoveField(
            model_name='game',
            name='demand_token_san_juan',
        ),
        migrations.RemoveField(
            model_name='game',
            name='demand_token_santo_domingo',
        ),
        migrations.RemoveField(
            model_name='game',
            name='demand_token_st_john',
        ),
        migrations.RemoveField(
            model_name='game',
            name='demand_token_st_maarten',
        ),
        migrations.RemoveField(
            model_name='game',
            name='demand_token_tortuga',
        ),
        migrations.RemoveField(
            model_name='game',
            name='demand_token_trinidad',
        ),
        migrations.AddField(
            model_name='game',
            name='demands_token',
            field=models.JSONField(blank=True, default=game.models.game.Game.sea_zones_list, null=True),
        ),
    ]
