# Generated by Django 5.0 on 2024-01-09 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0039_remove_game_demand_token_basse_terre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameDemandTokens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_round', models.IntegerField(default=0)),
                ('basse_terre', models.CharField(blank=True, max_length=20, null=True)),
                ('bridgetown', models.CharField(blank=True, max_length=20, null=True)),
                ('caracas', models.CharField(blank=True, max_length=20, null=True)),
                ('cartagena', models.CharField(blank=True, max_length=20, null=True)),
                ('curacao', models.CharField(blank=True, max_length=20, null=True)),
                ('nassau', models.CharField(blank=True, max_length=20, null=True)),
                ('havana', models.CharField(blank=True, max_length=20, null=True)),
                ('old_providence', models.CharField(blank=True, max_length=20, null=True)),
                ('petite_goave', models.CharField(blank=True, max_length=20, null=True)),
                ('port_royal', models.CharField(blank=True, max_length=20, null=True)),
                ('san_juan', models.CharField(blank=True, max_length=20, null=True)),
                ('santo_domingo', models.CharField(blank=True, max_length=20, null=True)),
                ('st_john', models.CharField(blank=True, max_length=20, null=True)),
                ('st_marteen', models.CharField(blank=True, max_length=20, null=True)),
                ('trinidad', models.CharField(blank=True, max_length=20, null=True)),
                ('tortuga', models.CharField(blank=True, max_length=20, null=True)),
                ('game_number', models.ForeignKey(blank=True, default=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.game')),
            ],
        ),
    ]
