# Generated by Django 5.0 on 2024-01-09 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0040_gamedemandtokens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='demands_token',
        ),
    ]
