# Generated by Django 5.0 on 2024-01-10 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0045_stacklargepirate'),
    ]

    operations = [
        migrations.AddField(
            model_name='stackeventscards',
            name='event_card_captain',
            field=models.BooleanField(default=False),
        ),
    ]
