# Generated by Django 5.0 on 2024-01-10 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0047_rename_large_pirate_stacklargepirate_captain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stackeventsnpccaptains',
            name='nationality',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
