# Generated by Django 5.0 on 2024-01-10 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0048_stackeventsnpccaptains_nationality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stacksmallpirate',
            name='captain',
        ),
        migrations.RemoveField(
            model_name='stacksmallpirate',
            name='game_number',
        ),
        migrations.DeleteModel(
            name='StackLargePirate',
        ),
        migrations.DeleteModel(
            name='StackSmallPirate',
        ),
    ]
