# Generated by Django 5.0 on 2024-01-10 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0049_remove_stacksmallpirate_captain_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackenemyhitlocations',
            name='game_round',
        ),
    ]
