# Generated by Django 5.0 on 2024-01-15 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0052_alter_shipslocalisations_blue_ship_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stackeventsnpccaptains',
            name='ship',
            field=models.CharField(blank=True, choices=[('Brig', 'Brig'), ('Flute', 'Flute'), ('Frigate', 'Frigate'), ('Galleon', 'Galleon'), ('Sloop', 'Sloop')], max_length=50, null=True),
        ),
    ]
