# Generated by Django 5.0 on 2024-01-22 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0055_alter_game_amount_players_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='player_blue_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='player_blue_play',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='player_green_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='player_green_play',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='player_red_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='player_red_play',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='player_yellow_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='player_yellow_play',
            field=models.BooleanField(default=False),
        ),
    ]
