# Generated by Django 5.0 on 2024-01-26 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0056_game_player_blue_done_game_player_blue_play_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='player_active_colour',
            field=models.CharField(blank=True, choices=[('blue', 'blue'), ('green', 'green'), ('red', 'red'), ('yellow', 'yellow')], max_length=30, null=True),
        ),
    ]
