# Generated by Django 5.0 on 2024-01-27 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0062_alter_game_player_active_colour'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerscaptainscards',
            name='player_active_colour',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='playerscaptainscards',
            name='player_blue_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playerscaptainscards',
            name='player_blue_play',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playerscaptainscards',
            name='player_green_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playerscaptainscards',
            name='player_green_play',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playerscaptainscards',
            name='player_red_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playerscaptainscards',
            name='player_red_play',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playerscaptainscards',
            name='player_yellow_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playerscaptainscards',
            name='player_yellow_play',
            field=models.BooleanField(default=False),
        ),
    ]
