# Generated by Django 5.0 on 2024-01-27 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0063_playerscaptainscards_player_active_colour_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerscaptainscards',
            name='player_active_colour',
        ),
        migrations.RemoveField(
            model_name='playerscaptainscards',
            name='player_blue_done',
        ),
        migrations.RemoveField(
            model_name='playerscaptainscards',
            name='player_blue_play',
        ),
        migrations.RemoveField(
            model_name='playerscaptainscards',
            name='player_green_done',
        ),
        migrations.RemoveField(
            model_name='playerscaptainscards',
            name='player_green_play',
        ),
        migrations.RemoveField(
            model_name='playerscaptainscards',
            name='player_red_done',
        ),
        migrations.RemoveField(
            model_name='playerscaptainscards',
            name='player_red_play',
        ),
        migrations.RemoveField(
            model_name='playerscaptainscards',
            name='player_yellow_done',
        ),
        migrations.RemoveField(
            model_name='playerscaptainscards',
            name='player_yellow_play',
        ),
    ]
