# Generated by Django 5.0 on 2024-01-28 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0064_remove_playerscaptainscards_player_active_colour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackplayergolds',
            name='player_blue',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='trackplayergolds',
            name='player_green',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='trackplayergolds',
            name='player_red',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='trackplayergolds',
            name='player_yellow',
            field=models.IntegerField(default=10),
        ),
    ]
