# Generated by Django 5.0 on 2024-01-28 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0065_alter_trackplayergolds_player_blue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='player_active_colour',
            field=models.CharField(blank=True, choices=[('blue', 'blue'), ('green', 'green'), ('red', 'red'), ('yellow', 'yellow')], max_length=30, null=True),
        ),
    ]
