# Generated by Django 5.0 on 2024-01-29 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0066_alter_game_player_active_colour'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayersActionsFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_blue_play', models.BooleanField(default=False)),
                ('player_blue_done', models.BooleanField(default=False)),
                ('player_green_play', models.BooleanField(default=False)),
                ('player_green_done', models.BooleanField(default=False)),
                ('player_red_play', models.BooleanField(default=False)),
                ('player_red_done', models.BooleanField(default=False)),
                ('player_yellow_play', models.BooleanField(default=False)),
                ('player_yellow_done', models.BooleanField(default=False)),
                ('player_active_colour', models.CharField(blank=True, choices=[('blue', 'blue'), ('green', 'green'), ('red', 'red'), ('yellow', 'yellow')], max_length=30, null=True)),
                ('game_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.game')),
            ],
        ),
    ]
