# Generated by Django 5.0 on 2024-01-29 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0067_playersactionsflow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='player_active_colour',
        ),
        migrations.RemoveField(
            model_name='game',
            name='player_blue_done',
        ),
        migrations.RemoveField(
            model_name='game',
            name='player_blue_play',
        ),
        migrations.RemoveField(
            model_name='game',
            name='player_green_done',
        ),
        migrations.RemoveField(
            model_name='game',
            name='player_green_play',
        ),
        migrations.RemoveField(
            model_name='game',
            name='player_red_done',
        ),
        migrations.RemoveField(
            model_name='game',
            name='player_red_play',
        ),
        migrations.RemoveField(
            model_name='game',
            name='player_yellow_done',
        ),
        migrations.RemoveField(
            model_name='game',
            name='player_yellow_play',
        ),
    ]
