# Generated by Django 5.0 on 2024-01-29 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0068_remove_game_player_active_colour_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='amount_players',
        ),
        migrations.RemoveField(
            model_name='game',
            name='round',
        ),
        migrations.AddField(
            model_name='playersactionsflow',
            name='amount_players',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playersactionsflow',
            name='rounds',
            field=models.IntegerField(default=0),
        ),
    ]
