# Generated by Django 5.0 on 2024-01-30 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0069_remove_game_amount_players_remove_game_round_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playersactionsflow',
            name='player_active_colour',
        ),
        migrations.AddField(
            model_name='playersactionsflow',
            name='player_blue_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playersactionsflow',
            name='player_green_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playersactionsflow',
            name='player_red_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playersactionsflow',
            name='player_yellow_active',
            field=models.BooleanField(default=False),
        ),
    ]
