# Generated by Django 5.0 on 2024-01-30 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0070_remove_playersactionsflow_player_active_colour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackenemyhitlocations',
            name='cannons',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trackenemyhitlocations',
            name='cargo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trackenemyhitlocations',
            name='crew',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trackenemyhitlocations',
            name='hull',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trackenemyhitlocations',
            name='masts',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
