# Generated by Django 5.0 on 2024-01-30 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0072_game_amount_players_game_player_blue_done_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamedemandtokens',
            name='game_round',
        ),
        migrations.RemoveField(
            model_name='gameshipmodifications',
            name='game_round',
        ),
        migrations.RemoveField(
            model_name='playerscaptainscards',
            name='game_round',
        ),
        migrations.RemoveField(
            model_name='playersglorycards',
            name='game_round',
        ),
        migrations.RemoveField(
            model_name='playersshipscards',
            name='game_round',
        ),
        migrations.RemoveField(
            model_name='shipslocalisations',
            name='game_round',
        ),
        migrations.RemoveField(
            model_name='stackeventscards',
            name='game_round',
        ),
        migrations.RemoveField(
            model_name='stackeventsnpccaptains',
            name='game_round',
        ),
        migrations.RemoveField(
            model_name='stackmissionscards',
            name='game_round',
        ),
        migrations.RemoveField(
            model_name='trackfavors',
            name='game_round',
        ),
        migrations.RemoveField(
            model_name='trackglorypoint',
            name='game_round',
        ),
        migrations.RemoveField(
            model_name='trackloyality',
            name='game_round',
        ),
        migrations.RemoveField(
            model_name='trackplayergolds',
            name='game_round',
        ),
        migrations.RemoveField(
            model_name='trackplayerhitlocations',
            name='game_round',
        ),
    ]
