# Generated by Django 5.0 on 2024-01-30 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0073_remove_gamedemandtokens_game_round_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stackeventscards',
            name='game_round',
            field=models.IntegerField(default=0),
        ),
    ]
