# Generated by Django 5.0 on 2024-02-02 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0074_stackeventscards_game_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipslocalisations',
            name='blue_in_port',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shipslocalisations',
            name='green_in_port',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shipslocalisations',
            name='red_in_port',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shipslocalisations',
            name='yellow_in_port',
            field=models.BooleanField(default=False),
        ),
    ]
