# Generated by Django 5.0 on 2024-02-04 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0075_shipslocalisations_blue_in_port_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipslocalisations',
            name='merchants',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
