# Generated by Django 5.0 on 2024-02-04 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0076_shipslocalisations_merchants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipslocalisations',
            name='merchants',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
