# Generated by Django 5.0 on 2024-02-05 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0079_alter_shipslocalisations_merchants'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipslocalisations',
            old_name='merchants',
            new_name='merchants_ship',
        ),
    ]
