# Generated by Django 5.0 on 2024-02-14 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0083_stackeventsnpccaptains_game_round'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='rounds',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
