# Generated by Django 5.0 on 2024-02-18 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0085_alter_game_rounds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playersglorycards',
            name='player_colour',
            field=models.CharField(blank=True, choices=[('blue', 'blue'), ('green', 'green'), ('red', 'red'), ('yellow', 'yellow')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='trackplayerhitlocations',
            name='player_colour',
            field=models.CharField(blank=True, choices=[('blue', 'blue'), ('green', 'green'), ('red', 'red'), ('yellow', 'yellow')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='TrackPlayerSpecialWeapons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_blue', models.JSONField(blank=True, default=list, null=True)),
                ('player_green', models.JSONField(blank=True, default=list, null=True)),
                ('player_red', models.JSONField(blank=True, default=list, null=True)),
                ('player_yellow', models.JSONField(blank=True, default=list, null=True)),
                ('game_number', models.ForeignKey(blank=True, default=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.game')),
            ],
        ),
    ]
