# Generated by Django 5.0 on 2024-02-18 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0086_alter_playersglorycards_player_colour_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackMerchantTokens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(blank=True, max_length=30, null=True)),
                ('second', models.CharField(blank=True, max_length=30, null=True)),
                ('thrith', models.CharField(blank=True, max_length=30, null=True)),
                ('fourth', models.CharField(blank=True, max_length=30, null=True)),
                ('fivth', models.CharField(blank=True, max_length=30, null=True)),
                ('sixth', models.CharField(blank=True, max_length=30, null=True)),
                ('seventh', models.CharField(blank=True, max_length=30, null=True)),
                ('eighth', models.CharField(blank=True, max_length=30, null=True)),
                ('game_number', models.ForeignKey(blank=True, default=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.game')),
            ],
        ),
    ]
