# Generated by Django 5.0 on 2024-02-23 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0088_trackplayershipmodifications'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TrackPlayerShipModifications',
            new_name='TrackPlayersShipModifications',
        ),
    ]
