# Generated by Django 5.0 on 2024-02-24 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataset', '0075_alter_cargocard_contraband_destination_and_more'),
        ('game', '0090_trackplayerbounties'),
    ]

    operations = [
        migrations.CreateModel(
            name='StackPlayerCargoCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_colour', models.CharField(blank=True, choices=[('blue', 'blue'), ('green', 'green'), ('red', 'red'), ('yellow', 'yellow')], max_length=20, null=True)),
                ('cargo_card_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='glory_card_1', to='dataset.cargocard')),
                ('cargo_card_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='glory_card_2', to='dataset.cargocard')),
                ('cargo_card_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='glory_card_3', to='dataset.cargocard')),
                ('cargo_card_4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='glory_card_4', to='dataset.cargocard')),
                ('cargo_card_5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='glory_card_5', to='dataset.cargocard')),
                ('cargo_card_6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='glory_card_6', to='dataset.cargocard')),
                ('cargo_card_7', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='glory_card_7', to='dataset.cargocard')),
                ('cargo_card_8', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='glory_card_8', to='dataset.cargocard')),
                ('game_number', models.ForeignKey(blank=True, default=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.game')),
            ],
        ),
    ]
