# Generated by Django 5.0 on 2024-02-24 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataset', '0075_alter_cargocard_contraband_destination_and_more'),
        ('game', '0091_stackplayercargocards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stackplayercargocards',
            name='cargo_card_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cargo_card_1', to='dataset.cargocard'),
        ),
        migrations.AlterField(
            model_name='stackplayercargocards',
            name='cargo_card_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cargo_card_2', to='dataset.cargocard'),
        ),
        migrations.AlterField(
            model_name='stackplayercargocards',
            name='cargo_card_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cargo_card_3', to='dataset.cargocard'),
        ),
        migrations.AlterField(
            model_name='stackplayercargocards',
            name='cargo_card_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cargo_card_4', to='dataset.cargocard'),
        ),
        migrations.AlterField(
            model_name='stackplayercargocards',
            name='cargo_card_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cargo_card_5', to='dataset.cargocard'),
        ),
        migrations.AlterField(
            model_name='stackplayercargocards',
            name='cargo_card_6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cargo_card_6', to='dataset.cargocard'),
        ),
        migrations.AlterField(
            model_name='stackplayercargocards',
            name='cargo_card_7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cargo_card_7', to='dataset.cargocard'),
        ),
        migrations.AlterField(
            model_name='stackplayercargocards',
            name='cargo_card_8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cargo_card_8', to='dataset.cargocard'),
        ),
    ]
