# Generated by Django 5.0 on 2024-03-06 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0094_alter_gamedemandtokens_basse_terre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamedemandtokens',
            name='basse_terre',
        ),
        migrations.RemoveField(
            model_name='gamedemandtokens',
            name='bridgetown',
        ),
        migrations.RemoveField(
            model_name='gamedemandtokens',
            name='caracas',
        ),
        migrations.RemoveField(
            model_name='gamedemandtokens',
            name='cartagena',
        ),
        migrations.RemoveField(
            model_name='gamedemandtokens',
            name='curacao',
        ),
        migrations.RemoveField(
            model_name='gamedemandtokens',
            name='gulf_city',
        ),
        migrations.RemoveField(
            model_name='gamedemandtokens',
            name='havana',
        ),
        migrations.RemoveField(
            model_name='gamedemandtokens',
            name='nassau',
        ),
        migrations.RemoveField(
            model_name='gamedemandtokens',
            name='old_providence',
        ),
        migrations.RemoveField(
            model_name='gamedemandtokens',
            name='petite_goave',
        ),
        migrations.RemoveField(
            model_name='gamedemandtokens',
            name='port_royal',
        ),
        migrations.RemoveField(
            model_name='gamedemandtokens',
            name='san_juan',
        ),
        migrations.RemoveField(
            model_name='gamedemandtokens',
            name='santo_domingo',
        ),
        migrations.RemoveField(
            model_name='gamedemandtokens',
            name='st_john',
        ),
        migrations.RemoveField(
            model_name='gamedemandtokens',
            name='st_maarten',
        ),
        migrations.RemoveField(
            model_name='gamedemandtokens',
            name='tortuga',
        ),
        migrations.RemoveField(
            model_name='gamedemandtokens',
            name='trinidad',
        ),
    ]
