# Generated by Django 5.0 on 2024-03-11 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0096_gamedemandtokens_basse_terre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameNav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_colour', models.CharField(blank=True, choices=[('blue', 'blue'), ('green', 'green'), ('red', 'red'), ('yellow', 'yellow')], max_length=30, null=True)),
                ('move', models.BooleanField(default=False)),
                ('to_port', models.BooleanField(default=False)),
                ('from_port', models.BooleanField(default=False)),
                ('to_sea_zone', models.BooleanField(default=False)),
                ('n_direction', models.BooleanField(default=False)),
                ('ne_direction', models.BooleanField(default=False)),
                ('e_direction', models.BooleanField(default=False)),
                ('se_direction', models.BooleanField(default=False)),
                ('s_direction', models.BooleanField(default=False)),
                ('sw_direction', models.BooleanField(default=False)),
                ('w_direction', models.BooleanField(default=False)),
                ('nw_direction', models.BooleanField(default=False)),
                ('scout', models.BooleanField(default=False)),
                ('merchant', models.BooleanField(default=False)),
                ('merchant_raid', models.BooleanField(default=False)),
                ('merchant_trade', models.BooleanField(default=False)),
                ('merchant_escort', models.BooleanField(default=False)),
                ('dutch_ship', models.BooleanField(default=False)),
                ('english_ship', models.BooleanField(default=False)),
                ('french_ship', models.BooleanField(default=False)),
                ('spanish_ship', models.BooleanField(default=False)),
                ('small_pirate_ship', models.BooleanField(default=False)),
                ('large_pirate_ship', models.BooleanField(default=False)),
                ('blue_player_ship', models.BooleanField(default=False)),
                ('green_player_ship', models.BooleanField(default=False)),
                ('red_player_ship', models.BooleanField(default=False)),
                ('yellow_player_ship', models.BooleanField(default=False)),
                ('port', models.BooleanField(default=False)),
                ('sell_goods', models.BooleanField(default=False)),
                ('but_goods', models.BooleanField(default=False)),
                ('visit_shipyard', models.BooleanField(default=False)),
                ('sell_buy_ship', models.BooleanField(default=False)),
                ('buy_special_weapon', models.BooleanField(default=False)),
                ('repair', models.BooleanField(default=False)),
                ('buy_ship_modification', models.BooleanField(default=False)),
                ('recruit', models.BooleanField(default=False)),
                ('acquire_a_rumor', models.BooleanField(default=False)),
                ('claim_a_mission', models.BooleanField(default=False)),
                ('stash_gold', models.BooleanField(default=False)),
                ('gain_loyality', models.BooleanField(default=False)),
                ('get_favour', models.BooleanField(default=False)),
                ('fishing', models.BooleanField(default=False)),
                ('visit_location', models.BooleanField(default=False)),
                ('back_to_port', models.BooleanField(default=False)),
                ('back', models.BooleanField(default=False)),
                ('end_turn', models.BooleanField(default=False)),
                ('game_number', models.ForeignKey(blank=True, default=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.game')),
            ],
        ),
    ]
