# Generated by Django 5.0 on 2024-03-12 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0097_gamenav'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GameNav',
        ),
    ]
