# Generated by Django 5.0 on 2024-03-27 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0100_gameport_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GamePort',
        ),
    ]
