# Generated by Django 5.0 on 2024-03-27 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0102_gameports'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameports',
            name='port_data',
            field=models.JSONField(default=dict),
        ),
    ]
