# Generated by Django 5.0 on 2024-03-27 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0103_gameports_port_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameports',
            name='port_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
