# Generated by Django 5.0 on 2024-01-05 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Player Board', max_length=150)),
                ('player_board', models.ImageField(blank=True, null=True, upload_to='player_board/')),
            ],
            options={
                'verbose_name': 'Player Board',
            },
        ),
    ]
