# Generated by Django 5.0 on 2024-01-05 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0022_alter_game_amount_players'),
        ('player_board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerboard',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.game'),
        ),
    ]
